### ISSUE TITLE
Vue Storefront <> Spree Integration

### ISSUE THREAD

**Issue by Shigawire** [spark-solutions/spree2vuestorefront#39]
After evaluating the vue-storefront-api codebase I figured out that the creators specifically created models for the Magento shop system:

https://github.com/DivanteLtd/vue-storefront-api/tree/master/src/platform/magento2

Would it make sense to create a similar platform module for spree? Especially with the spree API V2 JavaScript SDK this would allow a more seamless integration without going through additional proxy servers.

**Comment by tniezg** [comment]
@Shigawire That's true. Vue Storefront and VS-api primarily support Magento. I think platform integrations are a depreciated approach to integrating with VS. The core VS team wrote about it not being comfortable in practice: https://github.com/DivanteLtd/vue-storefront-integration-boilerplate#three-steps-of-integration.

In our case, we still have an intermediary Express server converting requests and responses, but requests from VS go directly to the server and from there directly to Spree.

**Comment by Shigawire** [comment]
@tniezg I understand. Thanks a lot for the reference! Makes total sense. As discussed on the Slack channel, I've had a similar approach to this through using AWS API Gateway + Lambda - that would receive the overhead of additional services to run and administrate (while creating operational and financial dependencies, though).
